import Head from "next/head";
import styles from "../styles/Home.module.scss";
import headshot from "../assets/images/headshot.jpeg";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <header className={styles.heading}>
          <span>RW.</span>
        </header>

        <section className={styles.hero}>
          <h1>Hi! I'm Russell</h1>
        </section>

        <div className={styles.photo}>
          <Image src={headshot} alt="Sitting in a hammock with my dog" />
        </div>

        <div className={styles.description}>
          <p>
            Welcome! I am a full-stack web developer based in beautiful B.C.
          </p>
          <p>
            I have a breadth of experience in Node.js (and TypeScript), focusing
            frontend work around React with a similar backend focus on Express.
            I've had time to explore GraphQL, Prisma, Next.js, MongoDb and
            PostgreSQL. I've made websites look nice using Tailwind and scss
            modules, and I've deployed websites using AWS (I have the AWS
            Developer Associate Certification), Heroku, Netlify, and probably a
            couple other services.
          </p>
          <p>
            Aside from coding I like to hang with my doggo and enjoy the
            outdoors we're blessed with in BC - mainly consists of
            walking/hiking when it's nice or snowboarding when it's the winter!
            I also enjoy reading (History/English degree - sorry, not sorry),
            music, taking mediocre pictures of cool places, and following
            basketball and football (both types - #FlyEaglesFly #HalaMadrid).
          </p>
        </div>
        <footer className={styles.footer}>
          <p>&copy; 2023 My Portfolio. All rights reserved.</p>
        </footer>
      </main>
    </>
  );
}
